site_name: iDiffuse
repo_url: https://github.com/gummiks/idiffuse
edit_uri: '#root'
extra_css: [extra.css]
theme: 
    name: readthedocs
    custom_dir: custom_theme
    include_sidebar: false
pages:
    - Home: index.md
    - Installation: installation.md
    - Getting Started: quickstart.md
    - Sizing Diffusers: diffuser_calculator.md
    - About Diffusers: about_diffusers.md
